class AddFeaturedcolumnsToBloggers < ActiveRecord::Migration[6.1]
  def change
    add_column :bloggers, :bl_feat_name_01, :string
    add_column :bloggers, :bl_feat_name_02, :string
    add_column :bloggers, :bl_feat_name_03, :string
    add_column :bloggers, :bl_feat_name_04, :string
    add_column :bloggers, :bl_feat_name_05, :string
    add_column :bloggers, :bl_feat_name_06, :string
    add_column :bloggers, :bl_feat_name_07, :string
    add_column :bloggers, :bl_feat_name_08, :string
    add_column :bloggers, :bl_feat_name_09, :string
    add_column :bloggers, :bl_feat_name_10, :string
    add_column :bloggers, :bl_feat_name_11, :string
    add_column :bloggers, :bl_feat_name_12, :string
    add_column :bloggers, :bl_feat_name_13, :string
    add_column :bloggers, :bl_feat_name_14, :string
    add_column :bloggers, :bl_feat_name_15, :string
    add_column :bloggers, :bl_feat_name_16, :string
    add_column :bloggers, :bl_feat_name_17, :string
    add_column :bloggers, :bl_feat_name_18, :string
    add_column :bloggers, :bl_feat_name_19, :string
    add_column :bloggers, :bl_feat_name_20, :string
    add_column :bloggers, :bl_feat_name_21, :string
    add_column :bloggers, :bl_feat_name_22, :string
    add_column :bloggers, :bl_feat_name_23, :string
    add_column :bloggers, :bl_feat_name_24, :string
    add_column :bloggers, :bl_feat_name_25, :string
    add_column :bloggers, :bl_feat_name_26, :string
    add_column :bloggers, :bl_feat_name_27, :string
    add_column :bloggers, :bl_feat_name_28, :string
    add_column :bloggers, :bl_feat_name_29, :string
    add_column :bloggers, :bl_feat_name_30, :string
    add_column :bloggers, :bl_feat_name_31, :string
    add_column :bloggers, :bl_feat_name_32, :string
    add_column :bloggers, :bl_feat_name_33, :string
    add_column :bloggers, :bl_feat_name_34, :string
    add_column :bloggers, :bl_feat_name_35, :string
    add_column :bloggers, :bl_feat_name_36, :string
    add_column :bloggers, :bl_feat_name_37, :string
    add_column :bloggers, :bl_feat_name_38, :string
    add_column :bloggers, :bl_feat_name_39, :string
    add_column :bloggers, :bl_feat_name_40, :string
    add_column :bloggers, :bl_feat_num_01, :float
    add_column :bloggers, :bl_feat_num_02, :float
    add_column :bloggers, :bl_feat_num_03, :float
    add_column :bloggers, :bl_feat_num_04, :float
    add_column :bloggers, :bl_feat_num_05, :float
    add_column :bloggers, :bl_feat_num_06, :float
    add_column :bloggers, :bl_feat_num_07, :float
    add_column :bloggers, :bl_feat_num_08, :float
    add_column :bloggers, :bl_feat_num_09, :float
    add_column :bloggers, :bl_feat_num_10, :float
    add_column :bloggers, :bl_feat_num_11, :float
    add_column :bloggers, :bl_feat_num_12, :float
    add_column :bloggers, :bl_feat_num_13, :float
    add_column :bloggers, :bl_feat_num_14, :float
    add_column :bloggers, :bl_feat_num_15, :float
    add_column :bloggers, :bl_feat_num_16, :float
    add_column :bloggers, :bl_feat_num_17, :float
    add_column :bloggers, :bl_feat_num_18, :float
    add_column :bloggers, :bl_feat_num_19, :float
    add_column :bloggers, :bl_feat_num_20, :float
    add_column :bloggers, :bl_feat_num_21, :float
    add_column :bloggers, :bl_feat_num_22, :float
    add_column :bloggers, :bl_feat_num_23, :float
    add_column :bloggers, :bl_feat_num_24, :float
    add_column :bloggers, :bl_feat_num_25, :float
    add_column :bloggers, :bl_feat_num_26, :float
    add_column :bloggers, :bl_feat_num_27, :float
    add_column :bloggers, :bl_feat_num_28, :float
    add_column :bloggers, :bl_feat_num_29, :float
    add_column :bloggers, :bl_feat_num_30, :float
    add_column :bloggers, :bl_feat_num_31, :float
    add_column :bloggers, :bl_feat_num_32, :float
    add_column :bloggers, :bl_feat_num_33, :float
    add_column :bloggers, :bl_feat_num_34, :float
    add_column :bloggers, :bl_feat_num_35, :float
    add_column :bloggers, :bl_feat_num_36, :float
    add_column :bloggers, :bl_feat_num_37, :float
    add_column :bloggers, :bl_feat_num_38, :float
    add_column :bloggers, :bl_feat_num_39, :float
    add_column :bloggers, :bl_feat_num_40, :float
  end
end
